User.create(email: "davedesch@gmail.com", first_name: "Dave", username: "DaveDesch", password: "password")
Picture.create(url: "http://i.imgur.com/12nrm5U.gif", caption: "Adell during morning announcements", user_id: 1)
Picture.create(url: "http://www.reactiongifs.com/wp-content/uploads/2013/12/pizza.gif", caption: "Talking to the staff about Game Night", user_id: 1)
Picture.create(url: "http://media.tumblr.com/tumblr_mea2rjZinu1re5zrmo1_500.gif", caption: "When your friends ask you to go out on the weekend." user_id: 1)
Picture.create(url: "http://media.tumblr.com/tumblr_m52n5vVuEQ1qhk2rc.gif", caption: "Phase 2 Lectures.", user_id: 1)
Picture.create(url: "http://i.imgur.com/d8IKT7f.gif?1826b3", caption: "When you try to fix something and end up making everything worse", user_id: 1)
Picture.create(url: "http://www.topito.com/wp-content/uploads/2013/01/code-21.gif", caption: "Spending all day on a project and it still doesn't work.", user_id: 1)
Picture.create(url: "http://3.bp.blogspot.com/-APYUgOqA_Os/UrVwG4Uw0UI/AAAAAAAAPbo/oKtnFQiRZCs/s1600/im-a-god.gif", caption: "When your first major project actually works." user_id: 1)
Picture.create(url: "http://1.bp.blogspot.com/-dCDeVSuJFqg/UZVVkkkZL5I/AAAAAAAAL14/G49n9JB5L1k/s1600/territory.gif", caption: "When a teammate changes a file they weren't supposed to work on and creates a merge conflict" user_id: 1)
Picture.create(url: "http://1.bp.blogspot.com/-ES8PEHXEjqo/URKyMYcppKI/AAAAAAAAJdA/LYoWQwsl_60/s1600/ketchup-bottle.gif" caption: "When you forget to terminate a recursive call", user_id: 1)
Picture.create(url: "http://1.bp.blogspot.com/-NmxSv-brC-I/UMoh1F7A_2I/AAAAAAAAD6s/Z1whmiDv2ts/s1600/stop-stop.gif", caption: "When new competencies keep getting introduced in Week 2", user_id: 1)
Picture.create(url: "http://2.bp.blogspot.com/-41v6n3Vaf5s/UeRN_XJ0keI/AAAAAAAAN2Y/YxIHhddGiaw/s1600/css.gif", caption: "CSS", user_id: 1)
Picture.create(url: "http://files.sharenator.com/Bug_reports_after_a_new_release-s300x225-410706-580a.gif", caption: "Phase 2. Week 2.", user_id: 1)