User.create(email: "davedesch@gmail.com", first_name: "Dave", username: "DaveDesch", password: "password")
Picture.create(url: "http://i.imgur.com/12nrm5U.gif", caption: "Adell during morning announcements", user_id: 1)
Picture.create(url: "http://www.reactiongifs.com/wp-content/uploads/2013/12/pizza.gif", caption: "Talking to the staff about Game Night", user_id: 1)
Picture.create(url: "http://media.tumblr.com/tumblr_mea2rjZinu1re5zrmo1_500.gif", caption: "When your friends ask you to go out on the weekend." user_id: 1)
Picture.create(url: "http://media.tumblr.com/tumblr_m52n5vVuEQ1qhk2rc.gif", caption: "Phase 2 Lectures.", user_id: 1)
Picture.create(url: "http://i.imgur.com/d8IKT7f.gif?1826b3", caption: "When you try to fix something and end up making everything worse", user_id: 1)
Picture.create(url: "http://www.topito.com/wp-content/uploads/2013/01/code-21.gif", caption: "Spending all day on a project and it still doesn't work.", user_id: 1)
Picture.create(url: "http://3.bp.blogspot.com/-APYUgOqA_Os/UrVwG4Uw0UI/AAAAAAAAPbo/oKtnFQiRZCs/s1600/im-a-god.gif", caption: "When your first major project actually works." user_id: 1)
Picture.create(url: "http://1.bp.blogspot.com/-dCDeVSuJFqg/UZVVkkkZL5I/AAAAAAAAL14/G49n9JB5L1k/s1600/territory.gif", caption: "When a teammate changes a file they weren't supposed to work on and creates a merge conflict" user_id: 1)
Picture.create(url: "http://1.bp.blogspot.com/-ES8PEHXEjqo/URKyMYcppKI/AAAAAAAAJdA/LYoWQwsl_60/s1600/ketchup-bottle.gif" caption: "When you forget to terminate a recursive call", user_id: 1)
Picture.create(url: "http://1.bp.blogspot.com/-NmxSv-brC-I/UMoh1F7A_2I/AAAAAAAAD6s/Z1whmiDv2ts/s1600/stop-stop.gif", caption: "When new competencies keep getting introduced in Week 2", user_id: 1)
Picture.create(url: "http://2.bp.blogspot.com/-41v6n3Vaf5s/UeRN_XJ0keI/AAAAAAAAN2Y/YxIHhddGiaw/s1600/css.gif", caption: "CSS", user_id: 1)
Picture.create(url: "http://files.sharenator.com/Bug_reports_after_a_new_release-s300x225-410706-580a.gif", caption: "Phase 2. Week 2.", user_id: 1)
Picture.create(url: "https://i.imgur.com/7PnuI2B.gif", caption: "When your pair is using Safari.", user_id: 1)
Picture.create(url: "https://gs1.wac.edgecastcdn.net/8019B6/data.tumblr.com/84ae984960e2a4e8b9a8349918b89394/tumblr_inline_nflncgLGO41ro2d43.gif", caption: "The Cohort's attitude after a few days of Phase 2.", user_id: 1)
Picture.create(url: "https://gs1.wac.edgecastcdn.net/8019B6/data.tumblr.com/394b6eb55f3e637618132cf0e738315b/tumblr_nby5h9D9o41s0my1wo1_500.gif", caption: "When a friend texts and asks how school is going", user_id: 1)
Picture.create(url: "http://media.tumblr.com/87d853172886e13fd5964af14eb52b88/tumblr_inline_new3y6ZckD1ro2d43.gif", caption: "Switching to JavaScript after 12 weeks of Ruby." user_id: 1)
Picture.create(url: "http://i.imgur.com/dvcxb.gif", caption: "When you're 100% sure what you wrote has no chance of working, then it does.", user_id: 1)
Picture.create(url: "https://gs1.wac.edgecastcdn.net/8019B6/data.tumblr.com/649a237d77e8ee1b2fc58592b9e93c01/tumblr_inline_nevpxyNXpE1ro2d43.gif", caption: "Getting used to counting the index of an array from 0", user_id: 1)
Picture.create(url: "https://i0.wp.com/herbookthoughts.reads-it.com/wp-content/uploads/2014/09/tumblr_n3pdrdhtN11rmtocio1_500.gif", caption: "Submitting portfolio challenges that aren't really done." user_id: 1)
Picture.create(url: "http://media.tumblr.com/ff8314b91120387811fe97999fb9a180/tumblr_inline_nc3szeJV1w1ro2d43.gif", caption: "When you thought you understood the lecture but then start the challenge." user_id: 1)
Picture.create(url: "http://ohthiskid.com/thedailymeal/tumblr_mctalko.gif" caption: "Every morning after working on a project until 3am.", user_id: 1)
Picture.create(url: "http://img2.wikia.nocookie.net/__cb20131102231616/vampirediaries/images/f/f1/Phil-Thumbs-Up.gif", caption: "When a coach saves your ass during a Sunday afternoon pairing session", user_id: 1)
Picture.create(url: "http://media.tumblr.com/111bd563590e6c001efd5fa7d5a2c0d2/tumblr_inline_n0en1cPPe51qbygev.gif", caption: "After the 2nd recursion breakout session", user_id: 1)
Picture.create(url: "http://honorslife.files.wordpress.com/2014/07/frantic-typing-gif.gif", caption: "Everyone at 4:15 when their project is due at 5.", user_id: 1)
Picture.create(url: "https://gs1.wac.edgecastcdn.net/8019B6/data.tumblr.com/6df913315a586739dfb62ec690f03146/tumblr_inline_n93sx5f5Sn1r79k32.gif", caption: "When people keep raising their hands after lecture is over", user_id: 1)
Picture.create(url: "http://s3-ec.buzzfed.com/static/2014-06/18/14/enhanced/webdr02/anigif_enhanced-buzz-26083-1403117436-23.gif", caption: "TDD.", user_id: 1)
Picture.create(url: "http://static.fjcdn.com/gifs/My+whole+brain+is+crying_d6368d_3364544.gif", caption: "Phase 2.", user_id: 1)
Picture.create(url: "https://gs1.wac.edgecastcdn.net/8019B6/data.tumblr.com/2744b1e911fd707b8dc20cf305c16e9f/tumblr_inline_n8m28myVUd1suw10y.gif", caption: "6:01pm every Graduation Friday.", user_id: 1)
Picture.create(url: "http://www.reactiongifs.com/r/eww.gif", caption: "When Brick reminds everyone the nap room is for napping only.", user_id: 1)